name: Qux

on:
  repository_dispatch:
    types: [qux-trigger]

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sleep
        run: sleep 30

      - name: Fail
        run:
          exit 1
